export interface Categories {
  ACAO: 'ACAO'
  AVENTURA: 'AVENTURA'
  COMEDIA: 'COMEDIA'
  DRAMA: 'DRAMA'
  DOCUMENTARIO: 'DOCUMENTARIO'
  TERROR: 'TERROR'
  SUSPENSE: 'SUSPENSE'
  FICCAO: 'FICCAO'
  ANIME: 'ANIME'
  ROMANCE: 'ROMANCE'
}
